import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { About } from "@/components/about/about";
import { Skills } from "@/components/skills/skills";
import { Education } from "@/components/education/education";
import { Certifications } from "@/components/certifications/certifications";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <About />
      </main>
      <section className={styles.mobileSection}>
        <Education />
        <Certifications />
        <Skills />
      </section>
    </>
  );
}
